// function test() {return 0;}
// str::text = "hello"+", world\n";
// str::text = null+"hello";
// str::text = "hello";
float[3]::a = [1.414, 2.236, 3.141];
// int::_i = 0;
// _i = _i + 1;
// float::_t = a[_i+2]; 
// function int::a(){}
// if (a <= 5) {
    // print(text+", world\n");
    // print(a+3+5 == 15 && a == 6+21);
    // float::char = print(text);
    // a[1] = 1;
    // b(1);
// float::b = 5+(-1);
// str::b = ("hello");
 float::b = a[-1+3];
    // a = a + 3;
// print("value: "+to_str(b)+'\n');
    // print(a);
    str::string = to_str(b);
    // float::a = 1;
    // print(to_str(a+3 == print("hello\n")*2 || (("hello, world") && a+1 == a*1))+'\n');
    // print(a || a);
    print(string+'\n');
// }
// test